"""Planner Agent - Task decomposition and management.

Breaks user goals into subtasks with deadlines using Vertex AI Gemini,
and manages tasks through the Google Tasks MCP server.
Persists created tasks to Firestore via TaskRepository.
"""

import json
import logging
from datetime import datetime, timedelta
from typing import Any

import vertexai
from vertexai.generative_models import GenerativeModel

from app.agents.base import AgentBase
from app.config import settings
from app.db.models import Task as TaskModel
from app.db.repositories import TaskRepository


logger = logging.getLogger(__name__)


PLANNER_PROMPT = """You are a task planning specialist. You either READ the user's existing tasks or CREATE new tasks. You must choose exactly one action.

ACTION SELECTION RULES (read carefully — this is critical):
- READ intent -> action: "list_tasks". The user wants to SEE, VIEW, or CHECK tasks that already exist. They are NOT asking you to make anything. In this case you MUST NOT create any tasks; return an EMPTY "tasks" array.
  Examples of READ: "what tasks do I have today?", "show my tasks", "list my todos", "do I have anything due?", "what's on my to-do list?", "any tasks for me?", "what do I need to do today?"
- WRITE intent -> action: "create_tasks". The user explicitly wants to ADD or CREATE something, or asks you to break a goal into steps.
  Examples of WRITE: "add a task to call the dentist", "create a task: finish report by Friday", "remind me to buy milk", "help me plan a launch party", "I need to prepare for the interview".
- When the user only wants to look at existing tasks, ALWAYS choose "list_tasks". Creating junk tasks for a read request is a serious error.
- For "create_tasks", create ONLY the tasks the user actually asked for. A single simple request = a single task. Only decompose into multiple subtasks when the user gives a broad goal that genuinely needs a plan. Never spam many tasks for a simple query.

Respond with a JSON object:
{
  "action": "list_tasks" | "create_tasks",
  "plan_summary": "brief description of the plan (create_tasks only)",
  "tasks": [
    {
      "title": "task title",
      "notes": "additional details or instructions",
      "due_days_from_now": number_of_days,
      "priority": "high|medium|low"
    }
  ],
  "response": "A natural language summary to share with the user"
}

For "list_tasks", set "tasks" to [] — the actual tasks are fetched from the user's account, not generated by you.
Each created task should be specific, actionable, and completable in one sitting.
"""


class PlannerAgent(AgentBase):
    """Planner agent that decomposes goals into tasks.

    Uses Vertex AI Gemini for intelligent task decomposition and the Google Tasks
    MCP server for task CRUD operations.
    """

    name = "planner"
    description = "Breaks goals into subtasks with deadlines"
    capabilities = ["task_decomposition", "task_creation", "task_listing"]

    def __init__(self, mcp_client: Any = None):
        """Initialize the planner with Vertex AI GenerativeModel.

        Args:
            mcp_client: Optional MCP client for tool access.
        """
        super().__init__(mcp_client)
        vertexai.init(project=settings.GCP_PROJECT_ID, location=settings.GCP_REGION)
        self.model = GenerativeModel(settings.GEMINI_MODEL)

    async def execute(self, task: dict) -> dict:
        """Read existing tasks or create new ones, based on user intent.

        Args:
            task: Dict with 'message' (the goal or instruction),
                  'auth_token' for Google API access,
                  'user_id' for Firestore persistence.

        Returns:
            Dict with 'content' (plan description or task list), 'agent' name,
            'action' taken, and 'tasks' (list of created/planned/listed tasks).
        """
        message = task.get("message", "")
        auth_token = task.get("auth_token", "")
        user_id = task.get("user_id", "")

        # Classify intent (READ vs WRITE) and, if writing, decompose the goal.
        plan = await self._analyze_request(message)
        action = plan.get("action", "create_tasks")

        # READ intent: list existing tasks, never create anything.
        if action == "list_tasks":
            tasks = await self.list_tasks(auth_token)
            return {
                "content": self._format_task_list(tasks),
                "agent": self.name,
                "action": "list_tasks",
                "tasks": tasks,
            }

        # WRITE intent: create the requested task(s).
        created_tasks = []
        if self.mcp_client and auth_token and plan.get("tasks"):
            for task_item in plan["tasks"]:
                try:
                    result = await self.call_mcp_tool(
                        "google-tasks",
                        "create_task",
                        {
                            "title": task_item["title"],
                            "notes": task_item.get("notes", ""),
                            "due_days_from_now": task_item.get("due_days_from_now", 7),
                            "auth_token": auth_token,
                        },
                    )
                    created_tasks.append(result)
                except Exception:
                    # Continue with other tasks even if one fails
                    pass

        # Persist tasks to Firestore
        persist_failures = 0
        if user_id and plan.get("tasks"):
            persist_failures = await self._persist_tasks_to_firestore(user_id, plan["tasks"])

        response_content = plan.get(
            "response", plan.get("plan_summary", "Plan created.")
        )

        if created_tasks:
            response_content += f"\n\nI've created {len(created_tasks)} task(s) in your Google Tasks."

        if persist_failures > 0:
            response_content += f"\n\nNote: {persist_failures} task(s) could not be saved to persistent storage."

        return {
            "content": response_content,
            "agent": self.name,
            "action": "create_tasks",
            "tasks": plan.get("tasks", []),
            "created_count": len(created_tasks),
            "persist_failures": persist_failures,
        }

    @staticmethod
    def _format_task_list(tasks: list[dict]) -> str:
        """Format a list of Google Tasks into a clean bulleted summary.

        Args:
            tasks: List of task dicts (may contain an error entry).

        Returns:
            A friendly, human-readable string. Handles the empty state.
        """
        real_tasks = [t for t in tasks if isinstance(t, dict) and not t.get("error")]

        if not real_tasks:
            return "You have no tasks today — want me to add one?"

        lines = [f"You have {len(real_tasks)} task(s):"]
        for t in real_tasks:
            indicator = "✓" if t.get("completed") else "○"
            title = t.get("title") or "Untitled task"
            line = f"• {indicator} {title}"
            due = t.get("due") or ""
            if due:
                # Google Tasks due dates are ISO timestamps; show just the date.
                line += f" (due {due[:10]})"
            lines.append(line)
        return "\n".join(lines)

    async def _persist_tasks_to_firestore(
        self, user_id: str, tasks: list[dict]
    ) -> int:
        """Persist planned tasks to Firestore.

        Args:
            user_id: The user ID to associate tasks with.
            tasks: List of task dictionaries from the plan.

        Returns:
            Number of tasks that failed to persist.
        """
        now = datetime.utcnow()
        failed_count = 0
        for task_item in tasks:
            try:
                due_days = task_item.get("due_days_from_now", 7)
                deadline = now + timedelta(days=due_days)
                task_model = TaskModel(
                    user_id=user_id,
                    title=task_item.get("title", ""),
                    description=task_item.get("notes", ""),
                    priority=task_item.get("priority", "medium"),
                    status="pending",
                    deadline=deadline,
                    created_at=now,
                    updated_at=now,
                )
                await TaskRepository.create(task_model)
            except Exception as e:
                failed_count += 1
                logger.warning(
                    "Failed to persist task '%s' for user '%s': %s",
                    task_item.get("title", "unknown"),
                    user_id,
                    str(e),
                )
        return failed_count

    async def _analyze_request(self, message: str) -> dict:
        """Classify the request as READ or WRITE and build a plan if writing.

        Args:
            message: The user's task-related message.

        Returns:
            Plan dictionary with 'action' ("list_tasks" | "create_tasks"),
            and for writes, 'tasks', 'plan_summary', and 'response'.
        """
        prompt = f"""{PLANNER_PROMPT}

User request: {message}"""

        text = await self.generate(
            prompt,
            generation_config={"response_mime_type": "application/json"},
            fallback="",
        )
        try:
            return json.loads(text)
        except Exception:
            # Safe fallback: when in doubt, READ rather than risk creating junk.
            return {
                "action": "list_tasks",
                "tasks": [],
                "response": "Let me pull up your tasks.",
            }

    async def list_tasks(self, auth_token: str) -> list[dict]:
        """List all tasks from Google Tasks.

        Args:
            auth_token: Google OAuth token for API access.

        Returns:
            List of task dictionaries.
        """
        if not self.mcp_client:
            return []

        try:
            result = await self.call_mcp_tool(
                "google-tasks", "list_tasks", {"auth_token": auth_token}
            )
            return result if isinstance(result, list) else []
        except Exception:
            return []
